# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Beverage.create({ name: "Old Fashion", ingredients: "Whisky, Sugar, Bitters", description: "Pre prohibition whisky cocktail that is both bitter and sweet deliciousness", image_url: "https://www.liquor.com/thmb/OdGMZLH9XqRF1_WzYCg8V_jvX38=/960x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__liquor__2018__05__08113350__bourbon-old-fashioned-720x720-recipe-ade6f7780c304999be3577e565c9bcdd.jpg" })
Beverage.create({ name: "Moscow Mule", ingredients: "Vodka, Ginger Beer, Lime", description: "Part of the mule family of cocktails meaning its mixed with ginger beer. Spicy and acidic ginger deliciousness", image_url: "https://cravingshappen.com/wp-content/uploads/2018/05/How-To-Make-A-Moscow-Mule-Recipe-4-1.jpg" })
Beverage.create({ name: "Jalapeno Margarita", ingredients: "Tequila, Jalapeno, Sourmix, Triple sec", description: "Like the classic margarita but SPICY! A go to for those who love acidic jalapeno deliciousness", image_url: "https://kitchenswagger.com/wp-content/uploads/2018/03/jalepeno-margarita1.jpg" })
Beverage.create({ name: "California Chardonnay", ingredients: "Grapes... You know... Cause it's wine...", description: "Known for its presence of a butter flavor and great tropical and stone fruit flavors. Dry, white, buttery deliciousness", image_url: "https://assets.dmagstatic.com/wp-content/uploads/2017/12/iStock-493586112-e1513610967667.jpg" })
Beverage.create({ name: "Whiteclaw", ingredients: "Carbonation, Fruit, Booze", description: "Why would you ever drink a beer again, There ain't no law when you're drinkin the claw, and Oh thank god. All things that you hear once people experience whiteclaw and you're next.", image_url: "https://thehustle.co/wp-content/uploads/2019/08/brief_2019-08-19T233023.760Z-1.jpg" })
Beverage.create({ name: "Oregon Pinot Noir", ingredients: "Grapes... You know... Cause it's wine...", description: "Bright red fruit forward flavor coming from the mild Oregon Climate.", image_url: "https://www.princeofpinot.com/media/images/06_43/06_43-13.jpg" })
Beverage.create({ name: "Negroni", ingredients: "Gin, Campari, Sweet Vermouth", description: "Fresh, botanical, and bitter all at the same time. Hints of grapefruit and cherry served on the rocks or up with an orange twist.", image_url: "https://www.liquor.com/thmb/FpQjWZNtBBC8PoW8aPfUj7cysYg=/720x720/filters:fill(auto,1)/__opt__aboutcom__coeus__resources__content_migration__liquor__2018__05__08110806__negroni-720x720-recipe-7c1b747a616f4659af4008d025ab55df.jpg" })
Beverage.create({ name: "Bourbon Berry Mule", ingredients: "Bourbon, Ginger Beer, Berries", description: "Berry twist on a Kentucky Mule! The bourbon makes it more bold than the Moscow Mule and the berries make it more fun!", image_url: "https://cookinglsl.com/wp-content/uploads/2015/08/moscow-mule-edited-1-1.jpg" })
Mood.create(name: "happy")
Mood.create(name: "sad")
Mood.create(name: "curious")
Mood.create(name: "tired")
Mood.create(name: "excited")
Taste.create(name: "sour")
Taste.create(name: "sweet")
Taste.create(name: "bitter")
Taste.create(name: "spicy")
Taste.create(name: "semi sweet")
Taste.create(name: "dry")
BeverageType.create(name: "beer")
BeverageType.create(name: "liquor")
BeverageType.create(name: "wine")
BeverageType.create(name: "non-alcoholic")
Flavor.create(name: "ginger")
Flavor.create(name: "lemon/lime")
Flavor.create(name: "apple")
Flavor.create(name: "berry")
Flavor.create(name: "mint")
Flavor.create(name: "cherry")
Flavor.create(name: "chocolate")
Flavor.create(name: "jalapeno")
Flavor.create(name: "grapefruit")
TasteFlavor.create(taste_id: 1, flavor_id: 2)
TasteFlavor.create(taste_id: 1, flavor_id: 4)
TasteFlavor.create(taste_id: 2, flavor_id: 3)
TasteFlavor.create(taste_id: 2, flavor_id: 4)
TasteFlavor.create(taste_id: 2, flavor_id: 6)
TasteFlavor.create(taste_id: 3, flavor_id: 5)
TasteFlavor.create(taste_id: 3, flavor_id: 7)
TasteFlavor.create(taste_id: 3, flavor_id: 9)
TasteFlavor.create(taste_id: 4, flavor_id: 1)
TasteFlavor.create(taste_id: 4, flavor_id: 8)
TasteFlavor.create(taste_id: 5, flavor_id: 3)
TasteFlavor.create(taste_id: 5, flavor_id: 6)
TasteFlavor.create(taste_id: 6, flavor_id: 1)
TasteFlavor.create(taste_id: 6, flavor_id: 2)
TasteFlavor.create(taste_id: 6, flavor_id: 3)
TasteFlavor.create(taste_id: 6, flavor_id: 6)
Prescription.create!({ mood_id: 5, beverage_type_id: 2, taste1_id: 1, taste2_id: 4, flavor_id: 2, beverage_id: 3 })
Prescription.create!({ mood_id: 4, beverage_type_id: 2, taste1_id: 2, taste2_id: 3, flavor_id: 6, beverage_id: 1 })
Prescription.create!({ mood_id: 3, beverage_type_id: 2, taste1_id: 1, taste2_id: 4, flavor_id: 1, beverage_id: 2 })
Prescription.create!({ mood_id: 3, beverage_type_id: 2, taste1_id: 3, taste2_id: 2, flavor_id: 9, beverage_id: 7 })
Prescription.create!({ mood_id: 3, beverage_type_id: 2, taste1_id: 1, taste2_id: 4, flavor_id: 4, beverage_id: 8 })
Prescription.create!({ mood_id: 1, beverage_type_id: 3, taste1_id: 6, taste2_id: 1, flavor_id: 3, beverage_id: 4 })
User.create!({ name: "Joey", email: "joey@test.com", password: "password", password_confirmation: "password" })
SavedBeverage.create!({ user_id: 1, beverage_id: 1 })
SavedBeverage.create!({ user_id: 1, beverage_id: 2 })
SavedBeverage.create!({ user_id: 1, beverage_id: 3 })
